In [8]:
%cd /home/jupyter/mnt/s3/databucket

/home/jupyter/mnt/s3/databucket


In [35]:
# %pip install pandas numpy torch scikit-learn nltk

In [1]:
%ls

Unigram Train-Copy1.png*
Unigram Train.png*
Untitled Folder/
bank-categories.csv*
bank-sentiment.csv*
banki.csv*
banks-ethic-DB - NEW.docx*
foo.pdf*
foo.png*
lightning_logs/
sentiment.csv*
source/
to.png*
train.csv*


In [2]:
# %pip install gensim

# Imports

In [2]:
import pandas as pd
import numpy as np
import re

import torch
from torchmetrics import AUROC
from torchmetrics import ROC
from collections import Counter
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score
from sklearn import decomposition
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import AgglomerativeClustering
from sklearn.cluster import KMeans

from gensim.models import Word2Vec, FastText


from sklearn.decomposition import PCA
from matplotlib import pyplot as plt
import plotly.graph_objects as go


import warnings
warnings.filterwarnings('ignore')

# unused but required import for doing 3d projections with matplotlib < 3.2
import mpl_toolkits.mplot3d  # noqa: F401
from nltk.stem.snowball import RussianStemmer
from nltk.tokenize import TweetTokenizer

# Constants

In [4]:
data='banki.csv'

In [3]:
VOCAB_SIZE = 7000

# Load Data

In [16]:


dataset = pd.read_csv('train.csv')
dataset = dataset.drop_duplicates()
#positive_tweets = pd.read_csv(
#    'positive.csv', header=None, delimiter=';')[[tweets_col_number]]
dataset_text=dataset.drop(['1category','2category','Unnamed: 0'],axis=1)
data_positive=dataset_text[dataset_text['sentiment']=='+']
data_negative=dataset_text[dataset_text['sentiment']=='−']
data_neutral=dataset_text[dataset_text['sentiment']=='?']

In [17]:
print(len(data_positive),len(data_negative),len(data_neutral))

6262 10192 2907


# Stemmer

In [18]:
stemer = RussianStemmer()
regex = re.compile('[^а-яА-Я ]')
stem_cache = {}

def get_stem(token):
    stem = stem_cache.get(token, None)
    if stem:
        return stem
    token = regex.sub('', token).lower()
    stem = stemer.stem(token)
    stem_cache[token] = stem
    return stem

# Create Vocabulary 

In [19]:
stem_count = Counter()
tokenizer = TweetTokenizer()

def count_unique_tokens_in_tweets(tweets):
    for _, tweet_series in tweets.iterrows():
        tweet = tweet_series[0]
        tokens = tokenizer.tokenize(tweet)
        for token in tokens:
            stem = get_stem(token)
            stem_count[stem] += 1

count_unique_tokens_in_tweets(data_positive)
count_unique_tokens_in_tweets(data_negative)
count_unique_tokens_in_tweets(data_neutral)

In [158]:
print("Total unique stems found: ", len(stem_count))

Total unique stems found:  8221


In [22]:
vocab = sorted(stem_count, key=stem_count.get, reverse=True)[:VOCAB_SIZE]
print(vocab[:100])

['', 'и', 'в', 'не', 'банк', 'на', 'что', 'я', 'с', 'эт', 'так', 'по', 'сотрудник', 'за', 'клиент', 'как', 'все', 'мне', 'карт', 'был', 'очен', 'а', 'к', 'котор', 'мо', 'мен', 'сво', 'у', 'отделен', 'он', 'работ', 'вопрос', 'прост', 'уж', 'от', 'ещ', 'но', 'о', 'дан', 'ответ', 'работа', 'раз', 'спасиб', 'до', 'обслуживан', 'сам', 'для', 'же', 'офис', 'то', 'отношен', 'при', 'даж', 'тольк', 'сбербанк', 'нет', 'услуг', 'вообщ', 'из', 'деньг', 'ни', 'сказа', 'больш', 'е', 'ваш', 'счет', 'друг', 'кредитн', 'хорош', 'получ', 'телефон', 'год', 'через', 'со', 'нич', 'говор', 'всегд', 'их', 'без', 'врем', 'быстр', 'посл', 'менеджер', 'т', 'никак', 'информац', 'когд', 'обращен', 'звон', 'удобн', 'сдела', 'приятн', 'ситуац', 'документ', 'услов', 'мы', 'специалист', 'вы', 'договор', 'перв']


In [23]:
idx = 2
print("stem: {}, count: {}"
      .format(vocab[idx], stem_count.get(vocab[idx])))

stem: в, count: 11095


In [24]:
len(vocab)

7000

In [25]:
token_2_idx = {vocab[i] : i for i in range(VOCAB_SIZE)}
len(token_2_idx)

7000

# Convert text to vectors

In [13]:
def tweet_to_vector(tweet, show_unknowns=False):
    vector = np.zeros(VOCAB_SIZE, dtype=np.int_)
    for token in tokenizer.tokenize(tweet):
        stem = get_stem(token)
        idx = token_2_idx.get(stem, None)
        if idx is not None:
            vector[idx] = 1
        elif show_unknowns:
            print("Unknown token: {}".format(token))
    return vector

In [164]:
tweet = data_positive.iloc[1][0]
print("tweet: {}".format(tweet))
print("vector: {}".format(tweet_to_vector(tweet)[:50]))
print(vocab[10])

tweet: Всегда в любое время дня и ночи помогут, ответят, решат.
vector: [1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 0 0]
так


In [165]:
data_negative.shape

(10192, 2)

In [166]:
tweet_vectors = np.zeros(
    (len(data_positive) + len(data_negative)+len(data_neutral), VOCAB_SIZE), 
    dtype=np.float32)
tweets = []
for ii, (_, tweet) in enumerate(data_positive.iterrows()):
    tweets.append(tweet[0])
    tweet_vectors[ii] = tweet_to_vector(tweet[0])
print('positive ok')

for ii, (_, tweet) in enumerate(data_negative.iterrows()):
    tweets.append(tweet[0])
    tweet_vectors[(ii + len(data_positive))] = tweet_to_vector(tweet[0])
print('negative ok')   

for ii, (_, tweet) in enumerate(data_neutral.iterrows()):
    tweets.append(tweet[0])
    tweet_vectors[ii + len(data_negative)+len(data_positive)] = tweet_to_vector(tweet[0])
print('neutral ok')

positive ok
negative ok
neutral ok


In [167]:
def to_vector(data,sennet_test):
    data_text=data.sentence
    VOCAB_SIZE=7000
    tweet_vectors = np.zeros(len(data_text), VOCAB_SIZE)
    dtype=np.float32tweets = []
    for ii, (_, tweet) in enumerate(data_text.iterrows()):
        tweets.append(tweet[0])
        tweet_vectors[ii] = tweet_to_vector(tweet[0])
    X = torch.from_numpy(tweet_vectors)
    
    return sennet_test.forward(X)
        
        
    
    

# Preparing labels

In [168]:


labels = np.append(
    np.zeros(len(data_positive), dtype=np.int64), 
    np.ones(len(data_negative), dtype=np.int64))

labels=np.append(labels,np.full(len(data_neutral),fill_value=2))

# Preparing the data for the training

In [171]:
X = torch.from_numpy(tweet_vectors)
y = torch.from_numpy(labels)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1)

# Creating a neural network architecture

In [29]:
class senNet(torch.nn.Module):
    def __init__(self):
        super(senNet,self).__init__()
        self.fc1=torch.nn.Linear(VOCAB_SIZE,256)
        self.act1=torch.nn.ReLU()
        self.fc2=torch.nn.Linear(256,120)
        self.act2=torch.nn.ReLU()
        self.fc3=torch.nn.Linear(120,3)
        
    
    def forward(self,x):
        x=self.fc1(x)
        x=self.act1(x)
        x=self.fc2(x)
        x=self.act2(x)
        x=self.fc3(x)
        return x

sen_net = senNet()

In [173]:
loss=torch.nn.CrossEntropyLoss()
optimizer=torch.optim.Adam(sen_net.parameters(), lr=1e-3)

# Training the neural network

In [174]:
batch_size = 100

test_accuracy_history = []
test_loss_history = []

# X_test = X_test.to(device)
# y_test = y_test.to(device)

from copy import deepcopy
best_acc = 0
for epoch in range(20):
    order = np.random.permutation(len(X_train))
    
    for start_index in range(0, len(X_train), batch_size):
        optimizer.zero_grad()
        
        batch_indexes = order[start_index:start_index+batch_size]
        
        X_batch = X_train[batch_indexes] #.to(device)
        y_batch = y_train[batch_indexes] #.to(device)
        
        preds = sen_net.forward(X_batch) 
        
        loss_value = loss(preds, y_batch)
        loss_value.backward()
        
        optimizer.step()
    
    
    test_preds = sen_net.forward(X_test)
    test_loss_history.append(loss(test_preds, y_test))
    
    accuracy = (test_preds.argmax(dim=1) == y_test).float().mean()
    test_accuracy_history.append(accuracy)
    print(accuracy)
    if best_acc < accuracy:
        print('Saving the best model')
        best_sen_net = deepcopy(sen_net)
        best_acc = accuracy
    
sen_net = best_sen_net  

tensor(0.8549)
Saving the best model
tensor(0.8694)
Saving the best model
tensor(0.8766)
Saving the best model
tensor(0.8756)
tensor(0.8771)
Saving the best model
tensor(0.8823)
Saving the best model
tensor(0.8849)
Saving the best model
tensor(0.8823)
tensor(0.8751)
tensor(0.8807)
tensor(0.8864)
Saving the best model
tensor(0.8854)
tensor(0.8833)
tensor(0.8864)
tensor(0.8823)
tensor(0.8813)
tensor(0.8751)
tensor(0.8828)
tensor(0.8849)
tensor(0.8751)


In [51]:
!ls

Unigram Train-Copy1.png
Unigram Train.png
Untitled Folder
bank-categories.csv
bank-sentiment.csv
banki.csv
banks-ethic-DB - NEW.docx
foo.pdf
foo.png
lightning_logs
sentiment.csv
source
to.png
train.csv


In [175]:
import os 
folder = os.path.join(os.getcwd(), "checkpoints")
if not os.path.exists(folder):
    os.mkdir(folder)
    
torch.save(best_sen_net, os.path.join(folder, 'best_senNet'))

In [53]:
os.getcwd()

'/home/jupyter/mnt/s3/databucket'

# Testing our neural network

In [177]:
preds=sen_net.forward(X_test)
auroc = AUROC(num_classes=3)
auroc(preds, y_test)

/usr/local/lib/python3.8/dist-packages/torchmetrics/utilities/prints.py:36: UserWarning: Metric `AUROC` will save all targets and predictions in buffer. For large datasets this may lead to large memory footprint.
  warnings.warn(*args, **kwargs)


tensor(0.9310)

In [ ]:
#tensor(0.9206)

In [179]:
def test_tweet(tweet):
    tweet_vector = tweet_to_vector(tweet, True)
    tweet_vector = torch.from_numpy(tweet_vector).float()
    print(tweet_vector)
    
    print('forw:',sen_net.forward(tweet_vector))
    positive_prob = sen_net.forward(tweet_vector)[1]
    max_index=sen_net.forward(tweet_vector).argmax()
    print('Original tweet: {}'.format(tweet))
    
    if max_index==0:
        print('result: Positive')
        
    elif max_index==1:
        print('result: Negative')
    elif max_index==2:
        print('result: Neutral')

In [180]:
tweets_for_testing = [
    "Ужасное приложение",
    "Я ухожу отсюда, сплошные мошенники",
    "Отвратительная поддержка",
    "Прекрасное приложение!",
    "Лучшее приложение в маркете!",
    "Не могу связаться с поддержкой банка.",
    "Приложение не открывается после обновления!!!!",
    "Приложение работоспособно"
]
for tweet in tweets_for_testing:
    test_tweet(tweet) 
    print("---------")

tensor([0., 0., 0.,  ..., 0., 0., 0.])
forw: tensor([-0.7388,  2.5109, -2.7085], grad_fn=<AddBackward0>)
Original tweet: Ужасное приложение
result: Negative
---------
tensor([1., 0., 0.,  ..., 0., 0., 0.])
forw: tensor([-5.8793,  2.0945,  1.7008], grad_fn=<AddBackward0>)
Original tweet: Я ухожу отсюда, сплошные мошенники
result: Negative
---------
tensor([0., 0., 0.,  ..., 0., 0., 0.])
forw: tensor([ 0.2627,  2.2579, -3.1562], grad_fn=<AddBackward0>)
Original tweet: Отвратительная поддержка
result: Negative
---------
tensor([1., 0., 0.,  ..., 0., 0., 0.])
forw: tensor([ 1.7443, -4.7332,  1.3335], grad_fn=<AddBackward0>)
Original tweet: Прекрасное приложение!
result: Positive
---------
Unknown token: маркете
tensor([1., 0., 1.,  ..., 0., 0., 0.])
forw: tensor([ 1.7214, -3.5448,  0.4578], grad_fn=<AddBackward0>)
Original tweet: Лучшее приложение в маркете!
result: Positive
---------
tensor([1., 0., 0.,  ..., 0., 0., 0.])
forw: tensor([-2.8241,  2.0625, -0.7222], grad_fn=<AddBackward0>)
O

## Testing again

In [58]:
def test_tweet(tweet):
    tweet_vector = tweet_to_vector(tweet, True)
    tweet_vector = torch.from_numpy(tweet_vector).float()
    print(tweet_vector)
    
    print('forw:',type(loaded_model))
    positive_prob = loaded_model.forward(tweet_vector)[1]
    print('Original tweet: {}'.format(tweet))
    print('P(positive) = {:.5f}. Result: '.format(positive_prob), 
          'Positive' if positive_prob > 0.5 else 'Negative')

In [59]:
tweets_for_testing = [
    "Ужасное приложение",
    "Я ухожу отсюда, сплошные мошенники",
    "Отвратительная поддержка",
    "Прекрасное приложение!",
    "Лучшее приложение в маркете!",
    "Не могу связаться с поддержкой банка.",
    "Приложение не открывается после обновления!!!"
]
for tweet in tweets_for_testing:
    test_tweet(tweet) 
    print("---------")

tensor([0., 0., 0.,  ..., 0., 0., 0.])


NameError: name 'loaded_model' is not defined

# SECOND Task

In [92]:

dataset = pd.read_csv('train.csv')
#positive_tweets = pd.read_csv(
#    'positive.csv', header=None, delimiter=';')[[tweets_col_number]]
dataset_text=dataset.drop(['sentiment','2category','Unnamed: 0'],axis=1)

data_com=dataset_text[dataset_text['1category']=='Communication']
data_quality=dataset_text[dataset_text['1category']=='Quality']
data_price=dataset_text[dataset_text['1category']=='Price']
data_safety=dataset_text[dataset_text['1category']=='Safety']

In [93]:
stemer = RussianStemmer()
regex = re.compile('[^а-яА-Я ]')
stem_cache = {}

def get_stem(token):
    stem = stem_cache.get(token, None)
    if stem:
        return stem
    token = regex.sub('', token).lower()
    stem = stemer.stem(token)
    stem_cache[token] = stem
    return stem

In [94]:
stem_count = Counter()
tokenizer = TweetTokenizer()
def count_unique_tokens_in_tweets(tweets):
    for _, tweet_series in tweets.iterrows():
        tweet = tweet_series[0]
        tokens = tokenizer.tokenize(tweet)
        for token in tokens:
            stem = get_stem(token)
            stem_count[stem] += 1
            
count_unique_tokens_in_tweets(data_com)
count_unique_tokens_in_tweets(data_quality)
count_unique_tokens_in_tweets(data_price)
count_unique_tokens_in_tweets(data_safety)

In [95]:
print("Total unique stems found: ", len(stem_count))

Total unique stems found:  7788


In [96]:
vocab = sorted(stem_count, key=stem_count.get, reverse=True)[:VOCAB_SIZE]
print(vocab[:100])

['', 'и', 'в', 'не', 'банк', 'на', 'что', 'я', 'с', 'эт', 'сотрудник', 'так', 'по', 'клиент', 'мне', 'за', 'как', 'все', 'а', 'очен', 'карт', 'котор', 'мо', 'был', 'мен', 'к', 'вопрос', 'сво', 'он', 'у', 'отделен', 'работ', 'ответ', 'прост', 'о', 'ещ', 'работа', 'уж', 'от', 'но', 'дан', 'обслуживан', 'раз', 'до', 'сам', 'то', 'при', 'офис', 'же', 'отношен', 'даж', 'спасиб', 'для', 'вообщ', 'тольк', 'нет', 'ни', 'услуг', 'деньг', 'сказа', 'из', 'е', 'друг', 'телефон', 'счет', 'нич', 'ваш', 'сбербанк', 'со', 'получ', 'говор', 'быстр', 'больш', 'врем', 'через', 'без', 'их', 'никак', 'звон', 'менеджер', 'информац', 'кредитн', 'посл', 'всегд', 'специалист', 'т', 'удобн', 'обращен', 'когд', 'хорош', 'решен', 'услов', 'проблем', 'могут', 'приятн', 'документ', 'год', 'очеред', 'поч', 'мы']


In [97]:
idx = 2
print("stem: {}, count: {}"
      .format(vocab[idx], stem_count.get(vocab[idx])))

stem: в, count: 8209


In [98]:
token_2_idx = {vocab[i] : i for i in range(VOCAB_SIZE)}
len(token_2_idx)

7000

In [99]:
tweet_vectors = np.zeros(
    (len(data_com) + len(data_quality)+len(data_price)+len(data_safety), VOCAB_SIZE), 
    dtype=np.float32
)
tweets = []

def tweet_to_vector(tweet, show_unknowns=False):
    vector = np.zeros(VOCAB_SIZE, dtype=np.int_)
    for token in tokenizer.tokenize(tweet):
        stem = get_stem(token)
        idx = token_2_idx.get(stem, None)
        if idx is not None:
            vector[idx] = 1
        elif show_unknowns:
            print("Unknown token: {}".format(token))
    return vector

for ii, (_, tweet) in enumerate(data_com.iterrows()):
    tweets.append(tweet[0])
    tweet_vectors[ii] = tweet_to_vector(tweet[0])
    
    
for ii, (_, tweet) in enumerate(data_quality.iterrows()):
    tweets.append(tweet[0])
    tweet_vectors[ii + len(data_com)] = tweet_to_vector(tweet[0])
    
for ii, (_, tweet) in enumerate(data_price.iterrows()):
    tweets.append(tweet[0])
    tweet_vectors[ii + len(data_com)+len(data_quality)] = tweet_to_vector(tweet[0])

for ii, (_, tweet) in enumerate(data_safety.iterrows()):
    tweets.append(tweet[0])
    tweet_vectors[ii + len(data_com)+len(data_quality)+len(data_price)] = tweet_to_vector(tweet[0])
print('ok')

ok


In [133]:
labels = np.append(
    np.zeros(len(data_com), dtype=np.int64), 
    np.ones(len(data_quality), dtype=np.int64))
labels=np.append(labels,np.full(len(data_price),fill_value=2))
labels=np.append(labels,np.full(len(data_safety),fill_value=3))
# 0 - communication
# 1 - quality
# 2 - price
# 3 - safety


In [101]:
X = torch.from_numpy(tweet_vectors)
y = torch.from_numpy(labels)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [55]:
class senNet2(torch.nn.Module):
    def __init__(self):
        super(senNet2,self).__init__()
        self.fc1=torch.nn.Linear(VOCAB_SIZE,256)
        self.act1=torch.nn.ReLU()
        self.fc2=torch.nn.Linear(256,120)
        self.act2=torch.nn.ReLU()
        self.fc3=torch.nn.Linear(120,4)
        
    
    def forward(self,x):
        x=self.fc1(x)
        x=self.act1(x)
        x=self.fc2(x)
        x=self.act2(x)
        x=self.fc3(x)
        return x

sen_net = senNet2()

In [103]:
loss=torch.nn.CrossEntropyLoss()
optimizer=torch.optim.Adam(sen_net.parameters(), lr=1.0e-3)

In [104]:
batch_size = 100

test_accuracy_history = []
test_loss_history = []

# X_test = X_test.to(device)
# y_test = y_test.to(device)

from copy import deepcopy
best_acc = 0
for epoch in range(20):
    order = np.random.permutation(len(X_train))
    
    for start_index in range(0, len(X_train), batch_size):
        optimizer.zero_grad()
        
        batch_indexes = order[start_index:start_index+batch_size]
        
        X_batch = X_train[batch_indexes] #.to(device)
        y_batch = y_train[batch_indexes] #.to(device)
        
        preds = sen_net.forward(X_batch) 
        
        loss_value = loss(preds, y_batch)
        loss_value.backward()
        
        optimizer.step()
    
    
    test_preds = sen_net.forward(X_test)
    test_loss_history.append(loss(test_preds, y_test))
    
    accuracy = (test_preds.argmax(dim=1) == y_test).float().mean()
    test_accuracy_history.append(accuracy)
    print(accuracy)
    if best_acc < accuracy:
        print('Saving the best model')
        best_sen_net = deepcopy(sen_net)
        best_acc = accuracy
    
sen_net = best_sen_net  

tensor(0.6844)
Saving the best model
tensor(0.6827)
tensor(0.6862)
Saving the best model
tensor(0.6706)
tensor(0.6676)
tensor(0.6750)
tensor(0.6701)
tensor(0.6671)
tensor(0.6683)
tensor(0.6673)
tensor(0.6644)
tensor(0.6661)
tensor(0.6671)
tensor(0.6648)
tensor(0.6653)
tensor(0.6629)
tensor(0.6567)
tensor(0.6673)
tensor(0.6616)
tensor(0.6663)


In [105]:
preds=sen_net.forward(X_test)
auroc = AUROC(num_classes=4)
auroc(preds, y_test)

/usr/local/lib/python3.8/dist-packages/torchmetrics/utilities/prints.py:36: UserWarning: Metric `AUROC` will save all targets and predictions in buffer. For large datasets this may lead to large memory footprint.
  warnings.warn(*args, **kwargs)


tensor(0.8045)

In [106]:
torch.save(best_sen_net, os.path.join(folder, 'best_senNet2'))

# Clustering banki.csv

In [188]:
#!g2.mig
dataset_cluster = pd.read_csv('banki.csv')
dataset_cluster

url_bank  ...              date
0       https://www.banki.ru/services/responses/bank/t...  ...  13.03.2021 22:19
1       https://www.banki.ru/services/responses/bank/t...  ...  11.03.2021 11:03
2       https://www.banki.ru/services/responses/bank/t...  ...  09.03.2021 23:10
3       https://www.banki.ru/services/responses/bank/t...  ...  01.03.2021 13:08
4       https://www.banki.ru/services/responses/bank/t...  ...  27.02.2021 22:08
...                                                   ...  ...               ...
593927  https://www.banki.ru/services/responses/bank/u...  ...  29.12.2007 10:39
593928  https://www.banki.ru/services/responses/bank/u...  ...   11.11.2007 0:18
593929  https://www.banki.ru/services/responses/bank/u...  ...  25.08.2007 22:17
593930  https://www.banki.ru/services/responses/bank/y...  ...  13.09.2019 14:20
593931  https://www.banki.ru/services/responses/bank/y...  ...  20.06.2008 13:44

[593932 rows x 4 columns]

In [189]:
dataset_cluster = dataset_cluster.drop_duplicates()

In [191]:
dataset_cluster_texts = dataset_cluster[['feeds']]
# просто сунь сразу все в модель

In [192]:
tweet_to_vector(dataset_cluster_texts.values[0][0])

array([1, 1, 1, ..., 0, 0, 0])

In [193]:
clust_vectors = np.zeros(
    (len(dataset_cluster_texts), VOCAB_SIZE), 
    dtype=np.float32)

chunk_size = 100
from tqdm import tqdm

for i, seq_ in tqdm(enumerate(dataset_cluster_texts.values), total = len(dataset_cluster_texts)):
    clust_vectors[i] = tweet_to_vector(seq_[0])


100%|██████████| 593921/593921 [12:51<00:00, 770.05it/s] 


In [194]:
clust_vectors

array([[1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       ...,
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 0., 1., ..., 0., 0., 0.],
       [1., 1., 0., ..., 0., 0., 0.]], dtype=float32)

In [ ]:
np.savetxt(
    os.path.join("checkpoints", "clust.txt"),
    clust_vectors
)

In [30]:
sen_net1=torch.load("checkpoints/best_senNet")
predx = torch.from_numpy(clust_vectors)
preds=sen_net1.forward(predx)
preds

tensor([[-2.4634e+00,  7.6616e-01,  6.4279e-01],
        [-5.7560e+00,  7.3058e+00, -5.3954e+00],
        [ 1.0515e+01, -1.0885e+01, -4.9720e+00],
        ...,
        [-4.8382e+00,  1.0816e-02,  2.1932e+00],
        [-1.0152e+01,  1.0624e+01, -6.1700e+00],
        [-1.5227e+01,  1.1858e+01, -3.8631e+00]], grad_fn=<AddmmBackward>)

In [34]:
import scipy 
prob_end = scipy.special.softmax(preds, axis=1)
prob_end

AttributeError: module 'scipy' has no attribute 'special'

# Submission

In [48]:
#!g2.mig
dataset_cluster = pd.read_csv('1sentencenewTRUE.csv',index_col=0)
dataset_cluster

0
0    15.03.2022 обратился на горячую линию для закр...
1    Уже который год в ТКБ не решается "глобальная ...
2                                          Добрый день
3    Добрый день Сегодня, зайдя в свой личный кабин...
4    Обслуживаюсь в Тинькофф пару лет, возникла жес...
..                                                 ...
944  Отвратительный сервис и отношение к клиентам! ...
945  28.04.2022 обратилась в банк о возможности пер...
946  В начале 2021 года была акция по выплате 8% ке...
947   Бездействие банка и некомпетентность сотрудников
948  Потрачено 5 часов чтобы произвести оплату за о...

[949 rows x 1 columns]

In [49]:
#!g2.mig
dataset_cluster_texts = dataset_cluster[['0']]
# просто сунь сразу все в модель

In [50]:
#!g2.mig
clust_vectors = np.zeros(
    (len(dataset_cluster_texts), VOCAB_SIZE), 
    dtype=np.float32)

chunk_size = 100
from tqdm import tqdm

for i, seq_ in tqdm(enumerate(dataset_cluster_texts.values), total = len(dataset_cluster_texts)):
    clust_vectors[i] = tweet_to_vector(seq_[0])

100%|██████████| 949/949 [00:05<00:00, 165.17it/s]


In [51]:
#!g2.mig
sen_net1=torch.load("checkpoints/best_senNet")
predx = torch.from_numpy(clust_vectors)
preds=sen_net1.forward(predx)
preds

tensor([[ 0.1485, -1.8145,  0.8918],
        [-2.9961,  3.3395, -2.3240],
        [-0.7746,  0.2841,  0.2042],
        ...,
        [ 2.9598, -7.0296,  1.4255],
        [-6.1427,  8.5474, -6.3569],
        [-4.6649,  9.2550, -8.4505]], grad_fn=<AddmmBackward>)

In [52]:
#!g2.mig
probs_end=torch.nn.functional.softmax(preds, dim=-1).detach().cpu().numpy()

In [53]:
#!g2.mig

dataset_cluster['+']=probs_end[:,0]
dataset_cluster['-']=probs_end[:,1]
dataset_cluster['?']=probs_end[:,2]
dataset_cluster

0  ...             ?
0    15.03.2022 обратился на горячую линию для закр...  ...  6.483796e-01
1    Уже который год в ТКБ не решается "глобальная ...  ...  3.452111e-03
2                                          Добрый день  ...  4.066858e-01
3    Добрый день Сегодня, зайдя в свой личный кабин...  ...  1.135268e-01
4    Обслуживаюсь в Тинькофф пару лет, возникла жес...  ...  3.967402e-10
..                                                 ...  ...           ...
944  Отвратительный сервис и отношение к клиентам! ...  ...  4.569076e-03
945  28.04.2022 обратилась в банк о возможности пер...  ...  2.018650e-01
946  В начале 2021 года была акция по выплате 8% ке...  ...  1.773501e-01
947   Бездействие банка и некомпетентность сотрудников  ...  3.366297e-07
948  Потрачено 5 часов чтобы произвести оплату за о...  ...  2.044641e-08

[949 rows x 4 columns]

In [56]:
#!g2.mig
sen_net2=torch.load("checkpoints/best_senNet2")
predx = torch.from_numpy(clust_vectors)
preds=sen_net2.forward(predx)
preds

tensor([[ 1.5395,  1.4487, -2.8075, -2.8412],
        [ 5.2867,  2.4216, -8.4367, -5.7852],
        [ 1.8852,  0.1260, -2.7884, -1.2874],
        ...,
        [ 3.4486,  3.2227, -6.5905, -5.5226],
        [ 1.0365,  0.4513, -1.8180, -1.2349],
        [ 1.4044,  3.8476, -4.7101, -4.8059]], grad_fn=<AddmmBackward>)

In [57]:
#!g2.mig
probs_end=torch.nn.functional.softmax(preds, dim=-1).detach().cpu().numpy()

In [58]:
#!g2.mig
# 0 - communication
# 1 - quality
# 2 - price
# 3 - safety
dataset_cluster['communication']=probs_end[:,0]
dataset_cluster['quality']=probs_end[:,1]
dataset_cluster['price']=probs_end[:,2]
dataset_cluster['safety']=probs_end[:,3]
dataset_cluster

0  ...    safety
0    15.03.2022 обратился на горячую линию для закр...  ...  0.006456
1    Уже который год в ТКБ не решается "глобальная ...  ...  0.000015
2                                          Добрый день  ...  0.034244
3    Добрый день Сегодня, зайдя в свой личный кабин...  ...  0.000475
4    Обслуживаюсь в Тинькофф пару лет, возникла жес...  ...  0.000098
..                                                 ...  ...       ...
944  Отвратительный сервис и отношение к клиентам! ...  ...  0.133006
945  28.04.2022 обратилась в банк о возможности пер...  ...  0.038021
946  В начале 2021 года была акция по выплате 8% ке...  ...  0.000071
947   Бездействие банка и некомпетентность сотрудников  ...  0.060063
948  Потрачено 5 часов чтобы произвести оплату за о...  ...  0.000161

[949 rows x 8 columns]

In [63]:
#!g2.mig
threshold = 0.3
dataset_cluster['second_category']=np.where(np.sort(probs_end, axis=-1)[:,-2]>threshold,1,0)
dataset_cluster

0  ...  second_category
0    15.03.2022 обратился на горячую линию для закр...  ...                1
1    Уже который год в ТКБ не решается "глобальная ...  ...                0
2                                          Добрый день  ...                0
3    Добрый день Сегодня, зайдя в свой личный кабин...  ...                0
4    Обслуживаюсь в Тинькофф пару лет, возникла жес...  ...                1
..                                                 ...  ...              ...
944  Отвратительный сервис и отношение к клиентам! ...  ...                1
945  28.04.2022 обратилась в банк о возможности пер...  ...                0
946  В начале 2021 года была акция по выплате 8% ке...  ...                1
947   Бездействие банка и некомпетентность сотрудников  ...                1
948  Потрачено 5 часов чтобы произвести оплату за о...  ...                0

[949 rows x 9 columns]

In [73]:
#!g2.mig
dataset_cluster.to_csv('/home/jupyter/work/resources/submission.csv',)

In [72]:
#!g2.mig
%ls /home/jupyter/work/resources/

11.multi-label-text-classification-with-bert.ipynb
Arslan/
Nik/
Sergey/
Untitled Folder/
Untitled.ipynb
checkpoints/
modeltraining_ru.ipynb
sentimentAnalysis.ipynb


In [ ]:
#!g2.mig


In [ ]:
#!g2.mig


In [37]:
#!g2.mig
import scipy as sp
banki_sentiment_pred_senNet1 = np.argmax(sp.special.softmax(preds, axis=1), axis=1)

AttributeError: module 'scipy' has no attribute 'special'

In [ ]:
#!g2.mig


In [ ]:
#!g2.mig


In [86]:
banki_preds = best_sen_net(
    torch.Tensor(clust_vectors)
)

TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.

In [424]:
corpus = []
for col in dataset_text.feeds:
    word_list = col.split(" ")
    corpus.append(word_list)

#show first value
corpus[0:1]

#generate vectors from corpus
model = Word2Vec(corpus, min_count=1, size = 56)

In [ ]:
X = model[model.wv.vocab]

In [434]:
kmeans = KMeans(n_clusters=5, random_state=0, n_init="auto").fit(X)

# Thank you for your attention!

In [346]:
%git remote add MED1024 <url>

fatal: not a git repository (or any parent up to mount point /home/jupyter/mnt/s3)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).


Exception: Process exited with code 128

In [339]:
import os
os.environ['github'] # secret github from environment variables

'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'